ur branch is main in ur fork smh

diff --git a/scripts/updater b/scripts/updater
--- a/scripts/updater
+++ b/scripts/updater
@@ -91,7 +91,7 @@ fi
 function performupdate() {
     # If init, then update_channel isn't set yet. Assume stable.
     if [ "$INIT" == true ]; then
-        update_channel="stable"
+        update_channel="main"
     else
         #get update channel from config
         exists=true
@@ -106,10 +106,8 @@ function performupdate() {
     # Store info about the currently checked out updater script hash
     OLD_UPDATE="$(git rev-parse HEAD:scripts/updater || echo invalid)"
 
-    if [ "$update_channel" == "stable" ]; then
-        git fetch --force --depth 1 origin refs/tags/stable:refs/tags/stable && git reset --hard stable || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 && git reset --hard @{upstream} || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. \n\033[0m"; exit 1; } }
-    elif [ "$update_channel" == "master" ]; then
-        git fetch --force --depth 1 origin && git reset --hard origin/master || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 && git reset --hard @{upstream} || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. \n\033[0m"; exit 1; } }
+    if [ "$update_channel" == "main" ]; then
+        git fetch --force --depth 1 origin && git reset --hard origin/main || { echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"; git fetch --depth 1 && git reset --hard @{upstream} || { echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. \n\033[0m"; exit 1; } }
     elif [ "$update_channel" == "developer" ]; then
         echo -e "\033[1;33m\nYou have been currectly Running Developer mode.\n\033[0m" && git pull origin --rebase=false || { echo -e "\033[1;31m\n\nFailed to pull from github!\n\033[0m"; exit 1; }
     else
